### ISSUE TITLE
App Not working with Vaadin 23.0.9

### ISSUE THREAD

**Issue by snaphalo** [FlowingCode/AppLayoutAddon#102]
I keep getting a blank page with [object, Object] in it. 
The error is: Type error cannot read properties of null (reading 'shadowRoot')

It seems that no example is working with Vaadin 23 and version 5.1.0. I've tried 14 with version 4.0.0 and everything is fine. I've tried Vaadin 22 (4.0.0) and everything worked as expected.

Thanks

**Comment by paodb** [comment]
Hello. I tested version 5.1.0 in a Vaadin 23.0.9 application and it works okay (see [applayouttest.zip](https://github.com/FlowingCode/AppLayoutAddon/files/8757895/applayouttest.zip)). If you're using Spring, please make sure you add `com.flowingcode` to the `vaadin.whitelisted-packages` property in your `application.properties` file.
Also we advice to run `mvn vaadin:dance` between every vaadin version change so node modules dependencies are update correctly.

**Comment by snaphalo** [comment]
Hello!
Thanks for the reply. Yes I've put com.flowingcode into the whitelisted-packages. I've tried with a brand new vaadin 23 install (todo demo). I will give your test a try later and let you know

Thanks for your time

**Comment by snaphalo** [comment]
Thank you very much for your help and the great addon. Seems that the problem was with the vaadin:dance. Didn't know about it.

Thanks!!!
