### ISSUE TITLE
slf4j-simple

### ISSUE THREAD

**Issue by LeshaRB** [FlowingCode/AppLayoutAddon#11]
```
<dependency>
            <groupId>org.slf4j</groupId>
            <artifactId>slf4j-simple</artifactId>
</dependency>
```
Is this dependence necessary?

In conjunction with Spring Boot, I must to exclude it
Can it be better for the user to provide a selection rule?

**Comment by javier-godoy** [comment]
Thanks. That dependency is not required by the addon itself (though it is used by the demo, with test scope). Fixed.
