### ISSUE TITLE
ReferenceError: drawer is not defined

### ISSUE THREAD

**Issue by gianluca-valentini** [FlowingCode/AppLayoutAddon#13]
Hi,
I installed the addon but I continue to have this error when click on MenuItems.

![image](https://user-images.githubusercontent.com/3224592/44905882-b2c46780-ad13-11e8-913c-b9db66f421c1.png)

![image](https://user-images.githubusercontent.com/3224592/44904889-bb676e80-ad10-11e8-950f-6e0fb0c65d7e.png)

I started from the Vaadin 10 Bakery where I change the mainView.html and MainView.java.
To modify the java code I followed the test class that is present on the repository even if in my case I extend PolymerTemplate

I also include the test custom-style in my shared-styles.html.

I'm using vaadin 10.0.4

Here the MainView.java snippet code:

`
@Tag("main-view")
@HtmlImport("src/main-view.html")
@HtmlImport("frontend://styles/shared-styles.html")
@Theme(Lumo.class)
@PageTitle("dashboardV10")
@Viewport(VIEWPORT)
public class MainView extends PolymerTemplate<TemplateModel> implements RouterLayout, BeforeEnterObserver {

	private static final long serialVersionUID = 1L;

	@Id("main")
	private Div div;

	private VerticalLayout main = new VerticalLayout();

	private VerticalLayout container = new VerticalLayout();
	private final AppLayout app = new AppLayout(new Image("/frontend/images/applogo.png", "avatar"), createAvatarComponent(), "AppLayout Vaadin 10 Demo");

	@Autowired
	public MainView(ConfirmDialog confirmDialog) {

		container.setDefaultHorizontalComponentAlignment(Alignment.CENTER);
		container.setSizeFull();

		main.setPadding(false);
		main.setSpacing(false);
		main.setMargin(false);

		app.setMenuItems(new MenuItem("About", "cloud", () -> showContent("About")));

		app.setToolbarIconButtons(new MenuItem(TITLE_LOGOUT, ICON_LOGOUT, () -> UI.getCurrent().navigate(PAGE_LOGOUT)),

				new MenuItem("Search", "search", () -> showContent("Search")),

				new MenuItem("Close", "close", () -> Notification.show("Close action"))

		);

		main.add(app, container);

		div.add(main);
	}
`

The html is attached
[main-view.zip](https://github.com/FlowingCode/AppLayoutAddon/files/2339536/main-view.zip)

Thanks
Gianluca

**Comment by LeshaRB** [comment]
I have the same error 
Version 1.0.4

**Comment by LeshaRB** [comment]
Ok I fix it

**Comment by mlopezFC** [comment]
Sorry for not answering you sooner. Without taking a deep look to this, it seems something unrelated to this addon, but I'm not sure. I also see that you commented that is already fixed. Do you still need some help or I can close the issue?
Thanks for the feedback, and sorry again for the delay.

**Comment by LeshaRB** [comment]
Thank you. No I change this AppLayoutAddon

**Comment by javier-godoy** [comment]
This should be fixed by #33
