### ISSUE TITLE
Support Vaadin Icons

### ISSUE THREAD

**Issue by claspina** [FlowingCode/AppLayoutAddon#14]
Can be possible to add support to using vaadin icons in menu item?

**Comment by javier-godoy** [comment]
It's already supported (since vaadin-icon works with iron-icon)

1. Add a dependency with Vaadin Icons
```
<dependency>
   <groupId>org.webjars.bowergithub.vaadin</groupId>
   <artifactId>vaadin-icons</artifactId>
   <version>4.2.0</version>
</dependency>
```

2. Import Vaadin Icons from the view 
```
@HtmlImport("frontend://bower_components/vaadin-icons/vaadin-icons.html")
```

3. Reference the icon using `vaadin:` prefix
```
new MenuItem("Test", "vaadin:vaadin-h", () -> {...})
```
