### ISSUE TITLE
Make app-header behavior configurable

### ISSUE THREAD

**Issue by mlopezFC** [FlowingCode/AppLayoutAddon#15]
It would be great if you could switch the app-header to float (scroll out the viewport) or fixed (stays visible) or auto (e.g. on viewport height).

**Comment by dmachollander** [comment]
Do you have a projected release date for 1.0.5?

**Comment by mlopezFC** [comment]
> Do you have a projected release date for 1.0.5?

We still need to analyze this further, so we don't have a release date for this enhancement. Do you need something specific related to this issue? ... or was it just a question about when the next release of this addon is going to happen?
Regards.

**Comment by dmachollander** [comment]
Looking for the scrolling and staying visible
