### ISSUE TITLE
Title overflows when the screen is too narrow

### ISSUE THREAD

**Issue by javier-godoy** [FlowingCode/AppLayoutAddon#29]
When the title is too long and the screen is too narrow, the title overflows the header.
![image](https://user-images.githubusercontent.com/11554739/50819648-73350a00-1309-11e9-9ea7-907d56f0f3e2.png)

Just adding ellipsis is not enough, since a couple of toolbar icons eat the available space.
![image](https://user-images.githubusercontent.com/11554739/50819846-fb1b1400-1309-11e9-9516-0ab1efd78a6c.png)

**Comment by javier-godoy** [comment]
Some space can be reclaimed from the toolbar by implementing https://github.com/FlowingCode/AppLayoutAddon/issues/42

However:
- The overflow only happens when the title breaks into three or more lines. If there are only two lines, there are no issues:
![image](https://user-images.githubusercontent.com/11554739/86471725-4a31e180-bd14-11ea-92ee-72cb08f71bcf.png)
- In normal mode, adding ellipsis forces the title to fit in a single line, which would be a worse outcome for medium-sized titles
![image](https://user-images.githubusercontent.com/11554739/86471893-92e99a80-bd14-11ea-8c18-c8ef7f18c0f7.png)
- In compact mode, only one line can fit, and adding ellipsis fixes the issue:
![image](https://user-images.githubusercontent.com/11554739/86473285-07bdd400-bd17-11ea-8c2f-5985009ba239.png)

I'm still undecided on what would be the expected behavior in normal mode.

**Comment by mlopezFC** [comment]
I think that the problem with normal mode is that the icon size for the logo is not the same size as the other icons. If the icon would be smaller (or the same size than the other ones), then having only one line with ellipsis would make sense. 
Another thing is that splitting in two lines would end up in the same problem if the title is *very* long. The title should always be in one line with ellipsis, if another behavior is needed, you could add your own <span> as a component and configure the title in the way it's needed.

**Comment by javier-godoy** [comment]
> if another behavior is needed, you could add your own as a component and configure the title in the way it's needed.

That feature is currently not implemented: the title is always a `String` and it cannot be replaced with a `Div` or another component because `AppToolbar` handles the wrapping. (It would be a good idea though, since it would enable breadcrumbs or other advanced use cases)

https://github.com/FlowingCode/AppLayoutAddon/blob/5d2785111c93bce677717071469549de8ec72bc6/src/main/java/com/flowingcode/addons/applayout/AppToolbar.java#L84

**Comment by mlopezFC** [comment]
Oh, yes, I was thinking about leaving the title empty and then adding a custom component to represent the title, but now I remember that they go to the right (because they are meant for creating toolbar things).
Anyway, giving that it's something that it would be nice to have in the future, maybe we could just leave it with ellipsis for now, what do you think?

**Comment by javier-godoy** [comment]
AbstractFcAppRouterLayout was removed in version 4.0.0 (#85). Now it's possible to add arbitrary components to the, title and they can be styled as needed.
