### ISSUE TITLE
Consider support for vaadin-router

### ISSUE THREAD

**Issue by mlopezFC** [FlowingCode/AppLayoutAddon#35]
It would be nice to have support for client-side navigation using vaadin-router.

**Comment by javier-godoy** [comment]
Can you detail this requirement a little bit more?

**Comment by mlopezFC** [comment]
Vaadin router is a component that intercepts anchor link clicks and instantiate web components for those demanded urls completely client side (without creating server requests).
Maybe a special mode for AppLayout could be configured, so it could be possible to create applications that with the first request creates the whole skeleton app with the AppLayout, and after that it can run like in an "offline" mode. 
In this way it could be possible to create PWAs that after showing the menu for the first time, then they could show error pages for destinations that needs server side interaction, but show cached content for help pages, etc.

**Comment by mlopezFC** [comment]
I'm closing this ticket, given that it's possible to use this approach without actually using the server-side addon
