### ISSUE TITLE
Z-Index

### ISSUE THREAD

**Issue by LeshaRB** [FlowingCode/AppLayoutAddon#5]
The menu is below the pages
<img width="540" alt="default" src="https://user-images.githubusercontent.com/439337/43085059-aa1abb46-8ea2-11e8-9252-aaf98a389fda.png">

**Comment by mlopezFC** [comment]
Hi! ... you can control the z-index in your shared-styles.html. [In the demo, the z-index is configured to 1000,](https://github.com/FlowingCode/AppLayoutAddon/blob/c799c936671455b44671401daf16b3f81b0d157a/src/test/resources/META-INF/resources/frontend/styles/shared-styles.html#L64) but you can try higher values in your project if that's not enough.

**Comment by LeshaRB** [comment]
Can make any theme by default? 
That there were no such questions.
