### ISSUE TITLE
Set spacing method does not use parameter

### ISSUE THREAD

**Issue by ngonzalezpazFC** [FlowingCode/AppLayoutAddon#61]
The [method ](https://github.com/FlowingCode/AppLayoutAddon/blob/ad4116cbe85861ca13affeceaf51b1f422bd39a9/src/main/java/com/flowingcode/addons/applayout/MenuItem.java#L137) in MenuItem class requires a value parameter of boolean type that is not used.
I think the parameter should be removed.

**Comment by javier-godoy** [comment]
You're right, but instead of just removing the parameter, `@Deprecate` the current method and have it invoke the correct way to set icon spacing, in order to avoid introducing a breaking change in the public API.
