### ISSUE TITLE
Refactor AppLayout as a client-side component

### ISSUE THREAD

**Issue by javier-godoy** [FlowingCode/AppLayoutAddon#64]
In order to support client-side use (e.g. vaadin-router #35) we need to provide AppLayout as a client-side component, instead of the current server-oriented approach.

**Comment by mlopezFC** [comment]
Given the existence of https://github.com/FlowingCode/fc-applayout I think we could close this ticket and open a new epic for the new version based on that, what do you think?

**Comment by javier-godoy** [comment]
I agree. This issue was about *providing* a client-side component, which is done in @flowingcode/fc-applayout. I created #67 for the actual refactoring.
