### ISSUE TITLE
Make AbstractFcAppRouterLayout.getTitle protected

### ISSUE THREAD

**Issue by javier-godoy** [FlowingCode/AppLayoutAddon#70]
Rename `getCaption` as `getTitle` in `AbstractFcAppRouterLayout` and make it `protected` instead of `private static`

https://github.com/FlowingCode/AppLayoutAddon/blob/e1754202c19c093afb4ad12f50a88518b7db79ef/src/main/java/com/flowingcode/addons/applayout/AbstractFcAppRouterLayout.java#L75

**Comment by mlopezFC** [comment]
Maybe it's better to call it "extractTitle" or "calculateTitle", because it's not just get it. Another thing is that it doesn't depend on the state of the object, is more like a utility method for extracting the title, isn't it better to remain static?

**Comment by javier-godoy** [comment]
> Maybe it's better to call it "extractTitle" 
+1

> Another thing is that it doesn't depend on the state of the object, is more like a utility method for extracting the title, isn't it better to remain static?

The suggestion of removing the `static` qualifier was in order to allow overriding the method

**Comment by javier-godoy** [comment]
AbstractFcAppRouterLayout was removed in version 4.0.0 (#85)
