### ISSUE TITLE
Parameterize welcome and redirect-welcome routes

### ISSUE THREAD

**Issue by javier-godoy** [FlowingCode/AppLayoutAddon#78]
The `welcome` and and `redirect-welcome` routes are hardcoded
	https://github.com/FlowingCode/AppLayoutAddon/blob/5c6df8fa6521f26c2dc30a883b407fe2eeb2288e/src/main/resources/META-INF/resources/frontend/fc-applayout/fc-fusion-layout.ts#L151-L153

**Comment by mlopezFC** [comment]
This mechanism was added because an iframe was used for keycloak integration. Maybe we should remove this feature for now.

**Comment by mlopezFC** [comment]
We discussed this. One way of doing this would be to add an attribute to the web component (fusion-layout) that would allow to use something different than "welcome" path.
